merchandisingSite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

polls/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = "polls"
urlpatterns = [ 
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path("/geolocation/", views.geolocation, name="geolocation"),
] 

polls/models.py
import datetime
import pandas as pd

from django.db import models
from django.utils import timezone
from django_google_maps import fields as map_fields

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

class GeolocationData(models.Model):
    id = models.IntegerField(primary_key=True)
    user_id = models.CharField(max_length=50)
    customer_code = models.CharField(max_length=100)
    customer_short_name = models.CharField(max_length=255)
    latitude = models.DecimalField(max_digits=9, decimal_places=6)
    longitude = models.DecimalField(max_digits=9, decimal_places=6)

    def __str__(self):
        return "{}".format(self.id)

polls/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from polls.models import Question, GeolocationData, Choice

import pandas as pd
import googlemaps
import json

class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"

    # return render(request, "polls/detail.html", { "question": question } )

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except(KeyError, Choice.DoesNotExist):
         # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def geolocation(request):
    geo_data = pd.read_csv("SampleFiles/sample-geolocation.csv")

    sample_data = geo_data[
        (geo_data.user_id == "wfsv02") 
    ].copy()

    return render(request, "polls/geolocation.html", {
        "sample_data": sample_data.to_json(orient="records"),
        "sample_data_html": sample_data.to_html()
    })

polls/templates/polls/detail.html
<h1>You are in Detail Page</h1>

<h2>{{ question.question_text }}</h2>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
  {% csrf_token %}
  {% for choice in question.choice_set.all %}
      <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
      <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
  {% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/geolocation.html
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <title>Directions service</title>
    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 100%;
      }
      /* Optional: Makes the sample page fill the window. */
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
      #floating-panel {
        position: absolute;
        top: 10px;
        left: 25%;
        z-index: 5;
        background-color: #fff;
        padding: 5px;
        border: 1px solid #999;
        text-align: center;
        font-family: 'Roboto','sans-serif';
        line-height: 30px;
        padding-left: 10px;
      }
    </style>
  </head>
  <body>
    <div id="floating-panel">
    <b>Start: </b>
    <select id="start">
    </select>
    <b>End: </b>
    <select id="end">
    </select>
    </div>
    <div id="map"></div>
    <script>
    var sampleData = null;

    function initMap() {
        var strSampleData = '{{ sample_data | safe }}';
        sampleData = JSON.parse(strSampleData);
        var originSelect = document.getElementById("start");
        var destSelect = document.getElementById("end");
        var html = "";

        for(var key in sampleData) {
            html += "<option value=" + sampleData[key].customer_code  + ">" +sampleData[key].customer_short_name + "</option>"
        }

        document.getElementById("start").innerHTML = html;
        document.getElementById("end").innerHTML = html;

        var directionsService = new google.maps.DirectionsService;
        var directionsDisplay = new google.maps.DirectionsRenderer;
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 7,
          center: {lat: 41.85, lng: -87.65}
        });
        directionsDisplay.setMap(map);

        var onChangeHandler = function() {
          calculateAndDisplayRoute(directionsService, directionsDisplay);
        };
        document.getElementById('start').addEventListener('change', onChangeHandler);
        document.getElementById('end').addEventListener('change', onChangeHandler);
    }

    function calculateAndDisplayRoute(directionsService, directionsDisplay) {
        var origin = document.getElementById('start').value;
        var destination = document.getElementById('end').value;
        var originLatLng = null;
        var destinationLatLng = null;

        //find LatLng in sampleData
        for(var key in sampleData){
            if(sampleData[key].customer_code == origin){
                originLatLng = new google.maps.LatLng(sampleData[key].latitude, sampleData[key].longitude);
            }

            if(sampleData[key].customer_code == destination){
                destinationLatLng = new google.maps.LatLng(sampleData[key].latitude, sampleData[key].longitude);
            }
        }

        directionsService.route({
          origin: originLatLng,
          destination: destinationLatLng,
          travelMode: 'DRIVING'
        }, function(response, status) {
          if (status === 'OK') {
            directionsDisplay.setDirections(response);
          } else {
            window.alert('Directions request failed due to ' + status);
          }
        });
    }
    </script>
    
    <div>
        <h2>Geolocation</h2>
        {{ sample_data_html | safe }}
    </div>
    
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDJTcmGDEdGXd4YpjYVFAwVux2biCxxPcY&callback=initMap">
    </script>
  </body>
</html>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

<h1> Geolocation Apps </h1>
<a href="{% url 'polls:geolocation' %}">Go to geolocation</a>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>